os:
  - osx
matrix:
  include:
    - osx_image: xcode7.3
language: node_js
node_js:
  - "6.14.2"
  - "8"
  - "stable"
  # node is latest
  - "node"
before_install:
# put local node-pre-gyp on PATH
- export PATH=./node_modules/.bin/:$PATH
# install node-gyp
- npm install node-gyp -g
# install node-pre-gyp-github
- npm install -g node-pre-gyp-github@1.3.1
# figure out if we should publish
- PUBLISH_BINARY=false
# if we are building a tag then publish
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;

install:
- yarn
# ensure source install works
- yarn build:source
# test our module
- yarn test

before_script:
# if publishing, do it
- if [[ $PUBLISH_BINARY == true ]]; then yarn build:package; yarn build:publish; fi;
# cleanup
- node-pre-gyp clean
- node-gyp clean
