os:
  - osx
language: node_js

jobs:
  include:
    - stage: test
      matrix:
        include:
          - osx_image: xcode7.3
      node_js:
        - "6.14.2"
        - "8"
        - "stable"

      before_install:
        # put local node-pre-gyp on PATH
        - export PATH=./node_modules/.bin/:$PATH
        # install node-gyp
        - npm install node-gyp -g
        # install node-pre-gyp-github
        - npm install -g node-pre-gyp-github@1.3.1
        # figure out if we should publish
        - PUBLISH_BINARY=false
        # if we are building a tag then publish
        - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;

      install:
        - yarn
        # ensure source install works
        - yarn build:source
        # test our module
        - yarn test

      before_script:
        # if publishing, do it
        - if [[ $PUBLISH_BINARY == true ]]; then yarn build:package; yarn build:publish; fi;

    - stage: deploy
      # Only build tags
      if: tag IS present
      node_js:
        - "stable"
      env:
        - NODE_RUNTIME=electron TARGET=2.0.0 DIST_URL=https://atom.io/download/atom-shell
      install:
        - yarn
        - yarn global add node-pre-gyp node-pre-gyp-github@1.3.1
        - node-pre-gyp configure --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp build --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp package --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp-github publish
