os:
  - osx
language: node_js

matrix:
  include:
    - osx_image: xcode7.3
node_js:
  - "6.14.2"
  - "8"
  - "stable"

install:
  - yarn
  # build from source
  - yarn build:source

jobs:
  include:
    - stage: deploy
      # Only build tags
      if: tag IS present
      node_js:
        - "stable"
      env:
        - NODE_RUNTIME=node TARGET=8.6.0
        - NODE_RUNTIME=electron TARGET=2.0.0 DIST_URL=https://atom.io/download/atom-shell
      install:
        - yarn
        - yarn global add node-pre-gyp node-pre-gyp-github@1.3.1
        - yarn build:source
        - node-pre-gyp configure --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp build --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp package --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
        - node-pre-gyp-github publish
